// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5IsaTAtYX-hjjXadq8f6Q0k4l2nBdhNo',
    appId: '1:10091030276:web:8d28930bd852a711875251',
    messagingSenderId: '10091030276',
    projectId: 'convene-9430a',
    authDomain: 'convene-9430a.firebaseapp.com',
    storageBucket: 'convene-9430a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBedrVl1XM_VTGRl2Ew9Po67nk0f5uoqeU',
    appId: '1:10091030276:android:f623a18f1e29a634875251',
    messagingSenderId: '10091030276',
    projectId: 'convene-9430a',
    storageBucket: 'convene-9430a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuSg16kU-tsgRXO9Qwzuu4L4K1IFpnVU4',
    appId: '1:10091030276:ios:b9e995ea5f5634d0875251',
    messagingSenderId: '10091030276',
    projectId: 'convene-9430a',
    storageBucket: 'convene-9430a.firebasestorage.app',
    iosBundleId: 'com.convene.convene',
  );
}
